export enum StorageKeys {
  NOTIFY_ON_CHANGE = "NOTIFY_ON_CHANGE",
  USE_TO_REFERENCE = "USE_TO_REFERENCE",
  OFFSET_PAGINATION_ENABLED = "OFFSET_PAGINATION_ENABLED",
  CURSOR_PAGINATION_ENABLED = "CURSOR_PAGINATION_ENABLED",
}
